### ISSUE TITLE
Turning the origami result around for face draw

### ISSUE THREAD

**Issue by suesslin** [Jugendhackt/TheJugendhacktOrigamiAlpaca#1]
How about drawing the face on the other site?

**Comment by jerik** [comment]
Hejho. Then you loose the alpaca framing. See the logo https://github.com/Jugendhackt. I had no 2-colored origami paper to show the intetion better. 1 Side white the other side blue.

**Comment by suesslin** [comment]
I believe it looks worse though.

**Comment by jerik** [comment]
Different people different taste :)

**Comment by suesslin** [comment]
What's the sense behind issues then?

**Comment by jerik** [comment]
Feel free to fork an do it your way :)
